# This external Configuration can now be references by different Deployments
apiVersion: v1
kind: ConfigMap
metadata:
    name: mongo-config
data:
  mongo-url: mongo-service # This will be the service name of MongoDB : will be the endpoint of MongoDB